### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by R4f4Lc** [runescapejon/SignLogger#1]
Only the person who places the poster is shown in the chat log. For example, user P4c0 places a poster and has permission to see the chat log. The user P4c0 is shown in the chat but not to the other users who have the permission to see the chat log

**Comment by runescapejon** [comment]
Oof sorry about that

**Comment by runescapejon** [comment]
https://ore.spongepowered.org/runescapejon/SignLogger/versions/1.2

sorry about that
