### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by R4f4Lc** [runescapejon/SignLogger#2]
https://github.com/runescapejon/SignLogger/blob/91feeebaba17536992931b88b995f9d2cf424cc3/src/main/java/me/runescapejon/signlogger/SignLogger.java#L131

You use Z Z Z in the log file and coords are bad. Use X Y Z. It's a good plugin. Good job!

**Comment by runescapejon** [comment]
Fixed, hahaha i find this funny that i totally over saw that lol 

Thanks <3
